apiVersion: v1
kind: Secret
metadata:
  name: postgres-config
  labels:
    app: postgres
type: Opaque
data:
  POSTGRES_DB: cG9zdGdyZXM=
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cEBzc3cwcmQ0Mg==