apiVersion: v1
kind: Secret
metadata:
  name: postgres-config
  labels:
    app: postgres
type: Opaque
data:
  POSTGRES_DB: {{ .Values.postgres.POSTGRES_DB }}
  POSTGRES_USER: {{ .Values.postgres.POSTGRES_USER}}
  POSTGRES_PASSWORD: {{ .Values.postgres.POSTGRES_PASSWORD }}