apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.name }}
  labels:
    app: {{ .Values.postgres.name }}
spec:
  selector:
    app: {{ .Values.postgres.name }}
  ports:
    - protocol: TCP
      name: http
      port: 5432
      targetPort: 5432